### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by svancise** [firstlinestats/api#1]
### Things to do
- [x] Game Page Graph
- [ ] Player Page Tables and Graphs 
- [ ] Team Pages
- [ ] Live Updates
- [ ] Ingest Previous Seasons
